-- Negative tests for whpg_dispatch_topology_file: the feature serves
-- hot-standby dispatchers ONLY.  On an ordinary primary QD the
-- component-table build refuses it outright (no silent fallback):
-- established dispatch sessions error at transaction start, brand-new
-- dispatch connections are refused at connect time, the state GUC
-- reports error, and a session holding temporary tables fails closed on
-- the topology transition instead of silently keeping a stale component
-- table.
--
-- The feature's positive suite lives in hot_standby/dispatch_topology,
-- where it runs on its real deployment shape (a hot-standby dispatcher).

-- start_matchsubs
-- m/dispatch topology file "[^"]*"/
-- s/dispatch topology file "[^"]*"/dispatch topology file "PATH"/
-- end_matchsubs

-- A well-formed file, to make it unambiguous that what is refused below
-- is the deployment shape, not the file.  NOTE: this catalog recipe is a
-- test convenience that only holds on a cluster with no failover history;
-- real files are generated by whpg-dr enable, which harvests each node's
-- own identity (gp_dbid from internal.auto.conf).
!\retcode psql -X -At -d postgres -c "select content, dbid, hostname, address, port, datadir from gp_segment_configuration where role='p' order by content" | tr '|' ' ' > "$COORDINATOR_DATA_DIRECTORY/whpg_dr_topology_test";

-- Establish both sessions BEFORE the topology appears; session 2 also
-- acquires a temp namespace.
1: show whpg_dispatch_topology_state;
2: create temp table topo_tmp(a int) distributed by (a);
2: insert into topo_tmp values (1), (2);

!\retcode gpconfig -c whpg_dispatch_topology_file -v whpg_dr_topology_test --coordinatoronly --skipvalidation;
!\retcode gpstop -u;

-- An established dispatch session: the component-table rebuild refuses
-- the feature at transaction start — even SHOW fails here (fail closed).
1: select 1;
1: show whpg_dispatch_topology_state;

-- A brand-new dispatch connection is refused at connect time (the build
-- runs during connection startup); only the exit code is asserted, the
-- FATAL carries the same message as above.
!\retcode psql -X -d isolation2test -c "select 1";

-- The temp-table session fails closed on the topology transition with a
-- message naming the way out, instead of silently keeping its stale
-- component table.
2: select count(*) from topo_tmp;

-- The state GUC, read from a utility session (the monitoring path),
-- reports error for this configuration.
-1U: show whpg_dispatch_topology_state;

-- Clearing the GUC restores stock behavior; both sessions recover, and
-- the temp namespace survived the episode untouched.
!\retcode gpconfig -r whpg_dispatch_topology_file --coordinatoronly --skipvalidation;
!\retcode gpstop -u;
1: select 1;
1: show whpg_dispatch_topology_state;
2: select count(*) from topo_tmp;
1q:
2q:

-- The recovery half of the handshake, exercised directly (no GUC needed:
-- the check arms itself on the presence of the topology fields in
-- gpqeid).  The crafted gpqeid carries coordinates in the shape a
-- topology dispatch would send, but arrives at a live primary: refused.
-- This simulates the wrong-cluster row: a DR replica is a physical clone
-- of its source, so a topology row pointing at the corresponding SOURCE
-- node carries a dbid and content its target genuinely has — recovery
-- state (standby.signal or recovery.signal, either entrance) is what
-- tells a replica from the live source.  (The recovery check fires
-- before the coordinate comparison, so it does not matter whether
-- dbid 1 / content -1 match this coordinator.)
! psql -X "dbname=postgres gpqeid=1;1;false;1;1;2;1;-1" -c "select 1" 2>&1 | grep -o "dispatch topology standby mismatch" | head -1;

-- The other legitimate entrance into recovery: recovery.signal -- the
-- shape of a whpg-dr replica, which runs targeted recovery held paused
-- at its restore point, so the signal file stays for the replica's whole
-- life.  A running primary never looks at the file (it is read at
-- startup only), so planting it here is safe; it is removed right after,
-- because left behind it would send the next restart into archive
-- recovery.  With the file present the same crafted gpqeid must fall
-- THROUGH the recovery check to the next line of defense, the dbid
-- check (99 is nobody's dbid): proof that a targeted-recovery replica
-- is an accepted dispatch target.  A check that demanded standby.signal
-- alone refused every healthy replica -- this pins the fix.
! touch "$COORDINATOR_DATA_DIRECTORY/recovery.signal";
! psql -X "dbname=postgres gpqeid=1;1;false;1;1;2;99;-1" -c "select 1" 2>&1 | grep -o "dispatch topology dbid mismatch" | head -1;
! rm -f "$COORDINATOR_DATA_DIRECTORY/recovery.signal";

!\retcode rm -f "$COORDINATOR_DATA_DIRECTORY/whpg_dr_topology_test";
