--
-- Additional tests for combocids, for sharing the the array between QE
-- processes, and for growing the array.
--
-- These tests are mostly copied from the upstream 'combocid' test, but
-- the SELECT queries are replaced with a more complicated query that runs
-- on two slices.
--
CREATE TEMP TABLE combocidtest (foobar int, distkey int) distributed by (distkey);

BEGIN;

-- a few dummy ops to push up the CommandId counter
INSERT INTO combocidtest SELECT 1 LIMIT 0;
INSERT INTO combocidtest SELECT 1 LIMIT 0;
INSERT INTO combocidtest SELECT 1 LIMIT 0;
INSERT INTO combocidtest SELECT 1 LIMIT 0;
INSERT INTO combocidtest SELECT 1 LIMIT 0;
INSERT INTO combocidtest SELECT 1 LIMIT 0;
INSERT INTO combocidtest SELECT 1 LIMIT 0;
INSERT INTO combocidtest SELECT 1 LIMIT 0;
INSERT INTO combocidtest SELECT 1 LIMIT 0;
INSERT INTO combocidtest SELECT 1 LIMIT 0;

INSERT INTO combocidtest VALUES (1);
INSERT INTO combocidtest VALUES (2);

SELECT ctid,cmin,* FROM combocidtest;

SAVEPOINT s1;

UPDATE combocidtest SET foobar = foobar + 10;

-- here we should see only updated tuples
SELECT * FROM combocidtest a, combocidtest b WHERE a.foobar < b.foobar;

ROLLBACK TO s1;

-- now we should see old tuples, but with combo CIDs starting at 0
SELECT * FROM combocidtest a, combocidtest b WHERE a.foobar < b.foobar;

COMMIT;

-- combo data is not there anymore, but should still see tuples
SELECT * FROM combocidtest a, combocidtest b WHERE a.foobar < b.foobar;

-- Test combo cids with portals
BEGIN;

INSERT INTO combocidtest VALUES (333);

DECLARE c CURSOR FOR SELECT * FROM combocidtest a, combocidtest b WHERE a.foobar < b.foobar;

DELETE FROM combocidtest;

FETCH ALL FROM c;

ROLLBACK;

SELECT * FROM combocidtest a, combocidtest b WHERE a.foobar < b.foobar;


--
-- Test growing the combocids array, including the shared combocids array.
--
CREATE TEMP TABLE manycombocids (i int, t text, distkey int) distributed by (distkey);
CREATE INDEX ON manycombocids (i);

BEGIN;

INSERT INTO manycombocids SELECT g, 'initially inserted',1 from generate_series(1, 10000) g;
ANALYZE manycombocids;

-- update some of the rows. The combocids generated by this are included in
-- the initial snapshot that the first FETCH acquires.
DO $$
declare
  j int;
begin
  set enable_seqscan=off;
  for j in 1..10 loop
    UPDATE manycombocids set t = 'updated1' where i = j;
  end loop;
end;
$$;

-- Launch a query that will scan the table, using a cursor.
--
-- Requirements for this test query:
--
-- - it should run on at least two slices, so that the combocids array is
--   shared between the QE processes
--
-- - it should return the rows in a deterministic order, because we use MOVE to
--   skip rows. This is just to keep the expected output reasonably short.
--
-- - it mustn't materialize the whole result on the first FETCH. Otherwise, the
--   reader processes won't see the combocids that are created only after the
--   first FETCH.
--
set enable_indexonlyscan=off;
set enable_indexscan=off;
set enable_bitmapscan=on;
explain (costs off)  SELECT a.i, b.i, a.t FROM manycombocids a, manycombocids b WHERE a.i = b.i AND a.distkey=1;
DECLARE c CURSOR FOR SELECT a.i, b.i, a.t FROM manycombocids a, manycombocids b WHERE a.i = b.i AND a.distkey=1;

-- Start the cursor.
FETCH 1 FROM c;

-- Perform more updates.
DO $$
declare
  j int;
begin
  set enable_seqscan=off;
  for j in 1..1000 loop
    UPDATE manycombocids set t = 'updated2' where i = j * 10;
  end loop;
end;
$$;

-- Run the cursor to completion. This will encounter the combocids generated by the
-- previous updates, and should correctly see that the updates are not visible to
-- the cursor. (MOVE to keep the expected output at a reasonable size.)
MOVE 9900 FROM c;
FETCH ALL FROM c;

rollback;

--
-- Test that the one-item tuple-visibility cache in heapgetpage() ignores
-- tuples carrying HEAP_COMBOCID.  Such a tuple's raw command id is an index
-- into the backend-local combo-CID array, not a real cmin, so it must not be
-- compared against another tuple's plain command id.
--
-- The scenario: a tuple whose deleting subtransaction aborted keeps its
-- combo cid, and a later scan sets the HEAP_XMAX_INVALID hint bit, which
-- used to make it eligible for the cache.  Combo-CID indexes and command
-- ids both count from zero, so the combo index easily collides with the
-- plain cmin of another tuple on the same page.  A cursor whose snapshot
-- lies between the two real cmins then returned a wrong extra row: the
-- plain tuple primed the cache and the combo tuple falsely hit it.
--
-- All rows use the same distribution key, so they land on the same segment
-- and the same heap page.  The cursor query scans a big table before the
-- table of interest (UNION ALL), so that the QE fills the motion send
-- buffer and blocks at DECLARE time, and only reaches the page of interest
-- during FETCH, after the hint bit has been set.
--
CREATE TEMP TABLE combocid_vischeck (a int, distkey int) distributed by (distkey);
CREATE TEMP TABLE combocid_vischeck_filler (x int, distkey int) distributed by (distkey);
CREATE TEMP TABLE combocid_vischeck_big (a int, distkey int) distributed by (distkey);
INSERT INTO combocid_vischeck_big SELECT 0, 0 FROM generate_series(1, 200000);

BEGIN;
INSERT INTO combocid_vischeck VALUES (1, 0);          -- cmin 0
INSERT INTO combocid_vischeck_filler VALUES (1, 0);   -- burn a command id
INSERT INTO combocid_vischeck_filler VALUES (2, 0);   -- burn a command id
DECLARE combocid_vischeck_cur CURSOR FOR
    SELECT a FROM combocid_vischeck_big UNION ALL SELECT a FROM combocid_vischeck;
INSERT INTO combocid_vischeck_filler VALUES (3, 0);   -- burn a command id
-- Insert before the savepoint, so the tuple keeps the main transaction's xmin.
INSERT INTO combocid_vischeck VALUES (2, 0);
SAVEPOINT s;
-- Assigns combo-CID index 0, colliding with the first row's cmin.
DELETE FROM combocid_vischeck WHERE a = 2;
ROLLBACK TO s;
-- This scan sets the HEAP_XMAX_INVALID hint bit (the deleter aborted).
SELECT count(*) FROM combocid_vischeck;
-- Skip past the big table's rows; the segment scans the page of interest
-- only now.  The cursor's snapshot predates the insertion of (2), so it
-- must see only (1).
MOVE 200000 FROM combocid_vischeck_cur;
FETCH ALL FROM combocid_vischeck_cur;
COMMIT;
